### PR TITLE
DS-213: added a timestamp to the AMQP message that is published when …

### PR DESCRIPTION
**Pull request by dennisroberts71**
…a user opens a data object

### CODE REVIEW

**Comment by tedgin** [comment]
A data object walks into a bar ...

**Comment by tedgin** [comment]
The change you made looks good, but would you mind adding an author object to the open message?

**Comment by dennisroberts71** [comment]
Sure, I could add one. I left it out in this case because the `accessor` and `author` are the same. I could either rename the field or keep both fields if that would be useful, though.

**Comment by tedgin** [comment]
The `author` field is a misnomer now that we've added a message about an action not causing a change.  It's supposed to be a common field that is part of every message identifying the client user. Being that `accessor` will always be the same as `author` please replace `accessor` with `author`, or maybe we could rename all `author` fields as something else, `actor`? `client`? `user`?  I'm just looking for consistency here.

**Comment by dennisroberts71** [comment]
Thanks. If we're looking for consistency, just changing the field name to `author` in this case would be least invasive fix. I'll make that change for the time being, and we can rename the field later if it causes confusion.

**Comment by tedgin** [comment]
Sounds good!

**Pull request merged**
